=== Zmate18/IN3BLK_XML-Gyak/XMLTaskIN3BLK/1. feladat/XMLSchemaIN3BLK.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- Saját típusok, egyszerű típusok -->
    <xs:element name="Emelet" type="xs:integer" />
    <xs:element name="Ar" type="xs:integer" />
    <xs:element name="Szabad" type="xs:string" />
    <xs:element name="Nev" type="xs:string" />
    <xs:element name="Telefon" type="TelefonszamTipus" />
    <xs:element name="Fizetes" type="xs:integer" />
    <xs:element name="Beosztas" type="xs:string" />
    <xs:element name="Cim" type="xs:string" />
    <xs:element name="Irszam" type="IranyitoszamTipus" />
    <xs:element name="Varos" type="xs:string" />
    <xs:element name="Utca-hazszam" type="xs:string" />
    <xs:element name="Ertekeles" type="xs:integer" />
    <xs:element name="Kezdet" type="DatumTipus" />
    <xs:element name="Vege" type="DatumTipus" />
    <xs:element name="Datum" type="DatumTipus" />
    <xs:element name="Fizetesmod" type="xs:string" />
    <xs:element name="Osszeg" type="xs:integer" />
    <xs:element name="Email" type="xs:string" />

    <xs:simpleType name="TelefonszamTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}-\d{2}-\d{3}-\d{4}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IranyitoszamTipus">
        <xs:restriction base="xs:integer">
            <xs:pattern value="\d{4}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="DatumTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}-\d{2}-\d{2}" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Komplex típusok -->
    <xs:complexType name="SzobaTipus">
        <xs:sequence>
            <xs:element name="Emelet" type="xs:integer" />
            <xs:element name="Ar" type="xs:integer" />
            <xs:element name="Szabad" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="sz_kod" type="xs:integer" />
    </xs:complexType>

    <xs:complexType name="AlkalmazottTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string" />
            <xs:element ref="Telefon" maxOccurs="unbounded" />
            <xs:element name="Fizetes" type="xs:integer" />
            <xs:element name="Beosztas" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HotelTipus">
        <xs:sequence>
            <xs:element ref="Nev" />
            <xs:element ref="Telefon" maxOccurs="unbounded" />
            <xs:element ref="Cim" />
                <xs:sequence>
                    <xs:element ref="Irszam" />
                    <xs:element ref="Varos" />
                    <xs:element ref="Utca-hazszam" />
                </xs:sequence>
            <xs:element ref="Ertekeles" />
        </xs:sequence>
        <xs:attribute name="h_kod" type="xs:integer" />
        <xs:attribute name="sz_kod" type="xs:integer" />
    </xs:complexType>

    <xs:complexType name="SzamlaTipus">
        <xs:sequence>
            <xs:element ref="Nev" />
            <xs:element ref="Datum" />
            <xs:element ref="Osszeg" />
        </xs:sequence>
        <xs:attribute name="szam_kod" type="xs:integer" />
        <xs:attribute name="v_kod" type="xs:integer" />
    </xs:complexType>

    <xs:complexType name="VevoTipus">
        <xs:sequence>
            <xs:element ref="Nev" />
            <xs:element ref="Telefon" maxOccurs="unbounded" />
            <xs:element ref="Email" />
        </xs:sequence>
        <xs:attribute name="v_kod" type="xs:integer" />
        <xs:attribute name="sz_kod" type="xs:integer" />
    </xs:complexType>

    <xs:complexType name="FoglalasTipus">
        <xs:sequence>
            <xs:element ref="Kezdet" />
            <xs:element ref="Vege" />
        </xs:sequence>
        <xs:attribute name="sz_kod" type="xs:integer" />
        <xs:attribute name="v_kod" type="xs:integer" />
    </xs:complexType>

    <xs:complexType name="FizetesTipus">
        <xs:sequence>
            <xs:element ref="Datum" />
            <xs:element ref="Fizetesmod" />
        </xs:sequence>
        <xs:attribute name="v_kod" type="xs:integer" />
        <xs:attribute name="szam_kod" type="xs:integer" />
    </xs:complexType>

    <!-- Gyökérelem -->
    <xs:element name="IN3BLK_Foglalas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Hotel" type="HotelTipus" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="Szoba" type="SzobaTipus" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="Alkalmazott" type="AlkalmazottTipus" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="Szamla" type="SzamlaTipus" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="Vevo" type="VevoTipus" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="Foglalas" type="FoglalasTipus" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="Fizetes" type="FizetesTipus" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>

        <!-- Elsődleges kulcsok -->
        <xs:key name="HotelPK">
            <xs:selector xpath="Hotel" />
            <xs:field xpath="@h_kod" />
        </xs:key>

        <xs:key name="SzobaPK">
            <xs:selector xpath="Szoba" />
            <xs:field xpath="@sz_kod" />
        </xs:key>

        <xs:key name="AlkalmazottPK">
            <xs:selector xpath="Alkalmazott" />
            <xs:field xpath="@a_kod" />
        </xs:key>

        <xs:key name="SzamlaPK">
            <xs:selector xpath="Szamla" />
            <xs:field xpath="@szam_kod" />
        </xs:key>

        <xs:key name="VevoPK">
            <xs:selector xpath="Vevo" />
            <xs:field xpath="@v_kod" />
        </xs:key>
        
        <xs:key name="FoglalasPK">
            <xs:selector xpath="Foglalas" />
            <xs:field xpath="@f_kod" />
        </xs:key>

        <xs:key name="FizetesPK">
            <xs:selector xpath="Fizetes" />
            <xs:field xpath="@fiz_kod" />
        </xs:key>

        <!-- Idegen kulcsok -->
        <xs:keyref name="HotelFK" refer="SzobaPK">
            <xs:selector xpath="Hotel" />
            <xs:field xpath="@sz_kod" />
        </xs:keyref>

        <xs:keyref name="AlkalmazottFK" refer="HotelPK">
            <xs:selector xpath="Alkalmazott" />
            <xs:field xpath="@h_kod" />
        </xs:keyref>

        <xs:keyref name="SzamlaFK" refer="VevoPK">
            <xs:selector xpath="Szamla" />
            <xs:field xpath="@v_kod" />
        </xs:keyref>

        <xs:keyref name="VevoFK" refer="SzoaPK">
            <xs:selector xpath="Vevo" />
            <xs:field xpath="@sz_kod" />
        </xs:keyref>

        <xs:keyref name="FoglalasSZFK" refer="SzobaPK">
            <xs:selector xpath="Foglalas" />
            <xs:field xpath="@sz_kod" />
        </xs:keyref>

        <xs:keyref name="FoglalasVFK" refer="VevoPK">
            <xs:selector xpath="Foglalas" />
            <xs:field xpath="@v_kod" />
        </xs:keyref>

        <xs:keyref name="FizetesSZFK" refer="SzamlaPK">
            <xs:selector xpath="Fizetes" />
            <xs:field xpath="@szam_kod" />
        </xs:keyref>

        <xs:keyref name="FizetesVFK" refer="VevoPK">
            <xs:selector xpath="Fizetes" />
            <xs:field xpath="@v_kod" />
        </xs:keyref>

    </xs:element>
</xs:schema>

=== Zmate18/IN3BLK_XML-Gyak/XMLTaskIN3BLK/DOMParseIN3BLK/XMLIN3BLK1.xml
<?xml version="1.0" encoding="UTF-8"?>
<IN3BLK_Foglalas xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaIN3BLK.xsd"> 

  <Szoba sz_kod="1">
    <Emelet >2</Emelet>
    <Ar >36000</Ar>
    <Szabad >Szabad</Szabad>
  </Szoba>

  <Szoba sz_kod="2">
    <Emelet >5</Emelet>
    <Ar >43000</Ar>
    <Szabad >Szabad</Szabad>
  </Szoba>

  <Szoba sz_kod="3">
    <Emelet >1</Emelet>
    <Ar >31000</Ar>
    <Szabad >Foglalt</Szabad>
  </Szoba>


  <Alkalmazott a_kod="1" h_kod="1">
    <Telefon >06-70-938-5617</Telefon>
    <Nev >Tóth András</Nev>
    <Ber >320000</Ber>
    <Beosztas >Portás</Beosztas>
  </Alkalmazott>

  <Alkalmazott a_kod="2" h_kod="2">
    <Telefon >06-30-294-7335</Telefon>
    <Telefon >06-20-993-3744</Telefon>
    <Nev >Lakatos Kevin</Nev>
    <Ber >390000</Ber>
    <Beosztas >Szakács</Beosztas>
  </Alkalmazott>

  <Alkalmazott a_kod="3" h_kod="3">
    <Telefon >06-70-223-9485</Telefon>
    <Nev >Szabó Ilona</Nev>
    <Ber >280000</Ber>
    <Beosztas >Takarító</Beosztas>
  </Alkalmazott>


  <Hotel h_kod="1" sz_kod="1">
    <Telefon >06-20-993-7766</Telefon>
    <Nev >Kényelem Hotel</Nev>
    <Cim >
      <Irszam >1028</Irszam>
      <Varos >Budapest</Varos>
      <Utca-hazszam >Szeles utca 25</Utca-hazszam>
    </Cim>
    <Ertekeles >3</Ertekeles>
  </Hotel>

  <Hotel h_kod="2" sz_kod="2">
    <Telefon >06-70-234-3443</Telefon>
    <Nev >Royal Hotel</Nev>
    <Cim >
      <Irszam >4033</Irszam>
      <Varos >Debrecen</Varos>
      <Utca-hazszam >Erdei utca 6</Utca-hazszam>
    </Cim>
    <Ertekeles >5</Ertekeles>
  </Hotel>

  <Hotel h_kod="3" sz_kod="3">
    <Telefon >06-30-345-2345</Telefon>
    <Telefon >06-30-999-2384</Telefon>
    <Nev >Udvari Hotel</Nev>
    <Cim >
      <Irszam >3521</Irszam>
      <Varos >Miskolc</Varos>
      <Utca-hazszam >Jakab utca 56</Utca-hazszam>
    </Cim>
    <Ertekeles >4</Ertekeles>
  </Hotel>


  <Szamla szam_kod="1" v_kod="1">
    <Nev >Kiss Anna</Nev>
    <Datum >2020-02-17</Datum>
    <Osszeg >86000</Osszeg>
  </Szamla>

  <Szamla szam_kod="2" v_kod="2">
    <Nev >Török András</Nev>
    <Datum >2021-09-10</Datum>
    <Osszeg >113000</Osszeg>
  </Szamla>

  <Szamla szam_kod="3" v_kod="3">
    <Nev >Horváth Áron</Nev>
    <Datum >2022-05-14</Datum>
    <Osszeg >93000</Osszeg>
  </Szamla>


  <Vevo sz_kod="1" v_kod="1">
    <Telefon >06-30-222-2345</Telefon>
    <Telefon >06-70-399-5577</Telefon>
    <Nev >Kiss Anna</Nev>
    <Email >kAnna@gmail.com</Email>
  </Vevo>

  <Vevo sz_kod="2" v_kod="2">
    <Telefon >06-20-948-3857</Telefon>
    <Telefon >06-30-947-5872</Telefon>
    <Nev >Török András</Nev>
    <Email >tAndras@freemail.hu</Email>
  </Vevo>

  <Vevo sz_kod="3" v_kod="3">
    <Telefon >06-70-993-6665</Telefon>
    <Nev >Horváth Áron</Nev>
    <Email >hAron@gmail.com</Email>
  </Vevo>


  <Foglalas sz_kod="1" v_kod="1">
    <Kezdet >2020-02-10</Kezdet>
    <Vege >2020-02-17</Vege>
  </Foglalas>

  <Foglalas sz_kod="2" v_kod="2">
    <Kezdet >2021-09-03</Kezdet>
    <Vege >2021-09-10</Vege>
  </Foglalas>

  <Foglalas sz_kod="3" v_kod="3">
    <Kezdet >2022-05-10</Kezdet>
    <Vege >2022-05-14</Vege>
  </Foglalas>


  <Fizetes szam_kod="1" v_kod="1">
    <Datum >2020-02-17</Datum>
    <Fizetesmod >Készpénz</Fizetesmod>
  </Fizetes>

  <Fizetes szam_kod="2" v_kod="2">
    <Datum >2021-09-10</Datum>
    <Fizetesmod >Bankkártya</Fizetesmod>
  </Fizetes>

  <Fizetes szam_kod="3" v_kod="3">
    <Datum >2022-05-14</Datum>
    <Fizetesmod >Bankkártya</Fizetesmod>
  </Fizetes>

</IN3BLK_Foglalas>

=== Zmate18/IN3BLK_XML-Gyak/XMLTaskIN3BLK/XMLIN3BLK.xml
<?xml version="1.0" encoding="utf-8"?>
<IN3BLK_Foglalas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="XMLSchemaIN3BLK.xsd">

    <!-- Szobák -->
    <Szoba sz_kod="1">
        <Emelet>2</Emelet>
        <Ar>36000</Ar>
        <Szabad>Szabad</Szabad>
    </Szoba>

    <Szoba sz_kod="2">
        <Emelet>5</Emelet>
        <Ar>43000</Ar>
        <Szabad>Szabad</Szabad>
    </Szoba>

    <Szoba sz_kod="3">
        <Emelet>1</Emelet>
        <Ar>31000</Ar>
        <Szabad>Foglalt</Szabad>
    </Szoba>

    <!-- Alkalmazottak -->
    <Alkalmazott a_kod="1" h_kod="1">
        <Nev>Tóth András</Nev>
        <Telefon>06-70-938-5617</Telefon>
        <Ber>320000</Ber>
        <Beosztas>Portás</Beosztas>
    </Alkalmazott>

    <Alkalmazott a_kod="2" h_kod="2">
        <Nev>Lakatos Kevin</Nev>
        <Telefon>06-30-294-7335</Telefon>
        <Telefon>06-20-993-3744</Telefon>
        <Ber>390000</Ber>
        <Beosztas>Szakács</Beosztas>
    </Alkalmazott>

    <Alkalmazott a_kod="3" h_kod="3">
        <Nev>Szabó Ilona</Nev>
        <Telefon>06-70-223-9485</Telefon>
        <Ber>280000</Ber>
        <Beosztas>Takarító</Beosztas>
    </Alkalmazott>

    <!-- Hotelek -->
    <Hotel h_kod="1" sz_kod="1">
        <Nev>Kényelem Hotel</Nev>
        <Telefon>06-20-993-7766</Telefon>
        <Cim>
            <Irszam>1028</Irszam>
            <Varos>Budapest</Varos>
            <Utca-hazszam>Szeles utca 25</Utca-hazszam>
        </Cim>
        <Ertekeles>3</Ertekeles>
    </Hotel>

    <Hotel h_kod="2" sz_kod="2">
        <Nev>Royal Hotel</Nev>
        <Telefon>06-70-234-3443</Telefon>
        <Cim>
            <Irszam>4033</Irszam>
            <Varos>Debrecen</Varos>
            <Utca-hazszam>Erdei utca 6</Utca-hazszam>
        </Cim>
        <Ertekeles>5</Ertekeles>
    </Hotel>

    <Hotel h_kod="3" sz_kod="3">
        <Nev>Udvari Hotel</Nev>
        <Telefon>06-30-345-2345</Telefon>
        <Telefon>06-30-999-2384</Telefon>
        <Cim>
            <Irszam>3521</Irszam>
            <Varos>Miskolc</Varos>
            <Utca-hazszam>Jakab utca 56</Utca-hazszam>
        </Cim>
        <Ertekeles>4</Ertekeles>
    </Hotel>

    <!-- Számlák -->
    <Szamla szam_kod="1" v_kod="1">
        <Nev>Kiss Anna</Nev>
        <Datum>2020-02-17</Datum>
        <Osszeg>86000</Osszeg>
    </Szamla>

    <Szamla szam_kod="2" v_kod="2">
        <Nev>Török András</Nev>
        <Datum>2021-09-10</Datum>
        <Osszeg>113000</Osszeg>
    </Szamla>

    <Szamla szam_kod="3" v_kod="3">
        <Nev>Horváth Áron</Nev>
        <Datum>2022-05-14</Datum>
        <Osszeg>93000</Osszeg>
    </Szamla>

    <!-- Vevők -->
    <Vevo v_kod="1" sz_kod="1">
        <Nev>Kiss Anna</Nev>
        <Telefon>06-30-222-2345</Telefon>
        <Telefon>06-70-399-5577</Telefon>
        <Email>kAnna@gmail.com</Email>
    </Vevo>

    <Vevo v_kod="2" sz_kod="2">
        <Nev>Török András</Nev>
        <Telefon>06-20-948-3857</Telefon>
        <Telefon>06-30-9475872</Telefon>
        <Email>tAndras@freemail.hu</Email>
    </Vevo>

    <Vevo v_kod="3" sz_kod="3">
        <Nev>Horváth Áron</Nev>
        <Telefon>06-70-993-6665</Telefon>
        <Email>hAron@gmail.com</Email>
    </Vevo>

    <!-- Foglalások -->
    <Foglalas sz_kod="1" v_kod="1">
        <Kezdet>2020-02-10</Kezdet>
        <Vege>2020-02-17</Vege>
    </Foglalas>

    <Foglalas sz_kod="2" v_kod="2">
        <Kezdet>2021-09-03</Kezdet>
        <Vege>2021-09-10</Vege>
    </Foglalas>

    <Foglalas sz_kod="3" v_kod="3">
        <Kezdet>2022-05-10</Kezdet>
        <Vege>2022-05-14</Vege>
    </Foglalas>
    
    <!-- Fizetések -->
    <Fizetes v_kod="1" szam_kod="1">
        <Datum>2020-02-17</Datum>
        <Fizetesmod>Készpénz</Fizetesmod>
    </Fizetes>

    <Fizetes v_kod="2" szam_kod="2">
        <Datum>2021-09-10</Datum>
        <Fizetesmod>Bankkártya</Fizetesmod>
    </Fizetes>

    <Fizetes v_kod="3" szam_kod="3">
        <Datum>2022-05-14</Datum>
        <Fizetesmod>Bankkártya</Fizetesmod>
    </Fizetes>
</IN3BLK_Foglalas>
